apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:25.0.2
        args:
        - start-dev
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_PROXY
          value: edge
        # - name: KEYCLOAK_IMPORT
        #   value: /opt/keycloak/data/import/realm-export.json # Specify the realm import file
        # - name: KC_THEME
        #   value: opea # Set the default theme to 'opea'
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        # volumeMounts:
        # - name: keycloak-realm
        #   mountPath: /opt/keycloak/data/import
        #   subPath: realm-export.json
        # - name: keycloak-theme
        #   mountPath: /opt/keycloak/themes/opea
        #   subPath: opea # Mount theme folder from ConfigMap
      volumes:
      - name: keycloak-realm
        configMap:
          name: keycloak-realm
      - name: keycloak-theme
        configMap:
          name: keycloak-theme
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
  - name: http
    nodePort: 31503
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: keycloak
  type: LoadBalancer
