- name: Setup GenAI Studio
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
  
    - name: Create studio namespace
      command: kubectl create namespace studio
      ignore_errors: yes

    - name: Check for coredns service
      shell: kubectl get svc coredns -n kube-system --ignore-not-found
      register: coredns_check
      ignore_errors: yes
      changed_when: false

    - name: Update manifest if coredns is available
      shell: sed -i 's/kube-dns/coredns/g' ../manifests/studio-manifest.yaml
      when: coredns_check.stdout != ''

    - name: Apply studio configuration
      command: kubectl apply -f ../studio-config.yaml

    - name: Apply customized studio manifest
      shell: "envsubst '${REGISTRY} ${TAG} ${HTTP_PROXY} ${NO_PROXY}' < ../manifests/studio-manifest.yaml | kubectl apply -f -"
      environment:
        REGISTRY: "{{ container_registry }}"
        TAG: "{{ container_tag }}"
        HTTP_PROXY: "{{ http_proxy }}"
        NO_PROXY: "{{ no_proxy }}"

    - name: Wait for all pods to be ready in studio namespace
      shell: kubectl wait --for=condition=ready pod --all --namespace=studio --timeout=180s
      register: pod_ready_check
      failed_when: pod_ready_check.rc != 0
      changed_when: false